const buildingsData = [
    { name: "Fire Station", quantity: 5 },
    { name: "Ambulance Station", quantity: 15 },
    { name: "Water Rescue", quantity: 2 },
    { name: "Police Station", quantity: 5 },
    { name: "Hospital", quantity: 4 },
    { name: "Lifeboat Station", quantity: 1 },
    { name: "Coastal Rescue Heliport", quantity: 0 },
    { name: "Medical Helicopter Station", quantity: 1 },
    { name: "Coastguard Rescue Station", quantity: 1 },
    { name: "HART Base", quantity: 1 },
    { name: "Foam Extension", quantity: 2 },
    { name: "Mass Casualty Extension", quantity: 3 },
    { name: "Police & Public Order Extension", quantity: 2 },
    { name: "Helicopter Hangar", quantity: 0 },
    { name: "Detention Unit Extension", quantity: 0 },
    { name: "Aviation firefighting Extension", quantity: 2 },
    { name: "Water Damage Pump Extension", quantity: 2 },
    { name: "Mud Rescue Extensions", quantity: 0 },
    { name: "Beach Lifeguard Extension", quantity: 0 },
    { name: "Hovercraft Extension", quantity: 0 },
    { name: "Search and Rescue HQ", quantity: 1 },
    { name: "Airfield Operations Extension", quantity: 4 },
    { name: "Aviation policing Extension", quantity: 2 },
    { name: "Recovery Centres", quantity: 3 },
    { name: "GP Surgery", quantity: 2 },
    { name: "Mountain Rescue Station", quantity: 1 },
    { name: "Railway fire response", quantity: 2 },
    { name: "HGV Recovery Extension", quantity: 3 },
    { name: "Railway Police", quantity: 2 }
];

const vehiclesData = [
    { name: "Ambulance", quantity: 42 },
    { name: "CARP", quantity: 10 },
    { name: "RRV", quantity: 10 },
    { name: "IRV", quantity: 10 },
    { name: "Recovery Vehicle", quantity: 8 },
      { name: "HGV Recovery Vehicle", quantity: 6 },
    { name: "Flatbed Recovery Vehicle", quantity: 6 },
    { name: "Joint Response Unit", quantity: 5 },
    { name: "Community Midwife", quantity: 5 },
    { name: "DSU", quantity: 4 },
    { name: "Water Ladder", quantity: 4 },
    { name: "ARV", quantity: 4 },
    { name: "RIV", quantity: 3 },
    { name: "Airfield Operations Supervisor", quantity: 3 },
    { name: "Major Foam Tender", quantity: 3 },
    { name: "Light 4x4", quantity: 3 },
    { name: "HEMS", quantity: 3 },
    { name: "Fire Officer", quantity: 3 },
    { name: "OTL", quantity: 3 },
    { name: "Airfield Firefighting Command Vehicle", quantity: 2 },
    { name: "Armed Traffic Car", quantity: 2 },
    { name: "ATV Carrier", quantity: 2 },
    { name: "General Practitioner", quantity: 2 },
    { name: "Mountain Rescue 4x4", quantity: 2 },
    { name: "Aerial Appliance", quantity: 2 },
    { name: "CBRN Vehicle", quantity: 2 },
    { name: "EIU", quantity: 2 },
    { name: "Boat Trailer", quantity: 2 },
    { name: "Mass Casualty Equipment", quantity: 2 },
    { name: "Mounted Unit", quantity: 2 },
    { name: "Police helicopter", quantity: 2 },
    { name: "RP CAFS", quantity: 2 },
    { name: "Traffic Car", quantity: 2 },
    { name: "RRU", quantity: 2 },
    { name: "Medical equipment trailer", quantity: 2 },
    { name: "Search Dog Unit", quantity: 2 },
    { name: "Ambulance Officer", quantity: 2 },
    { name: "Ambulance Control Unit", quantity: 2 },
    { name: "SRV", quantity: 1 },
    { name: "WrL CAFS", quantity: 1 },
    { name: "Operational Support Trailer", quantity: 1 },
    { name: "ILB", quantity: 1 },
    { name: "Detention Van", quantity: 1 },
    { name: "Welfare Vehicle", quantity: 1 },
    { name: "Pump Trailer", quantity: 1 },
    { name: "SAR 4x4", quantity: 1 },
    { name: "CRV", quantity: 1 },
    { name: "Search Dog Unit (SAR)", quantity: 1 },
    { name: "Patient Transport Service Ambulance", quantity: 1 },
    { name: "4x4 Vehicle", quantity: 1 },
    { name: "Inland Rescue Boat (Trailer)", quantity: 1 },
    { name: "Co-Responder Vehicle", quantity: 1 },
    { name: "PM", quantity: 1 },
    { name: "Multiple Dog Carrier", quantity: 1 },
    { name: "PRV", quantity: 1 },
    { name: "Control Van (Mountain Rescue)", quantity: 1 },
    { name: "Airfield Operations Vehicle", quantity: 1 },
    { name: "Rescue Watercraft (Trailer)", quantity: 1 },
    { name: "Control Van (SAR)", quantity: 1 },
    { name: "Hovercraft Transporter", quantity: 1 },
    { name: "Specialist Paramedic RRV", quantity: 1 },
    { name: "Rescue Stairs", quantity: 1 },
    { name: "HVP", quantity: 1 },
    { name: "Drone Vehicle (Police Station)", quantity: 1 },
    { name: "Rescue Support Unit (RSU)", quantity: 1 }
];

const staffData = [
    { name: "ARFF", quantity: 40 },
    { name: "Ambulance Officer", quantity: 33 },
    { name: "Co-Responder", quantity: 20 },
    { name: "Coastal Commander", quantity: 20 },
    { name: "Critical care", quantity: 74 },
      { name: "Dog handler", quantity: 20 },
    { name: "Dog handling", quantity: 69 },
    { name: "Drone Operator", quantity: 4 },
    { name: "Firearms training", quantity: 59 },
    { name: "Flood First Responder", quantity: 10 },
    { name: "HART Training", quantity: 43 },
    { name: "HazMat Unit", quantity: 49 },
    { name: "High Volume Pump Operator", quantity: 20 },
    { name: "Hovercraft Commander", quantity: 10 },
    { name: "Jet Ski Driver", quantity: 10 },
    { name: "Level 1 Incident Commander Training", quantity: 24 },
    { name: "Level 1 Public Order Officer", quantity: 4 },
    { name: "Level 2 Public Order Officer", quantity: 5 },
    { name: "Lifeboat Operator", quantity: 10 },
    { name: "Lifeguard", quantity: 44 },
    { name: "Midwife", quantity: 29 },
    { name: "Mobile Operations Manager", quantity: 19 },
    { name: "Mounted Officers", quantity: 14 },
    { name: "Police Inspector", quantity: 24 },
    { name: "Police Medic", quantity: 2 },
    { name: "Police Sergeant", quantity: 15 },
    { name: "Police aviation", quantity: 13 },
    { name: "Railway Fire", quantity: 37 },
    { name: "Railway Police Officer", quantity: 29 },
    { name: "Roads Policing Officer", quantity: 39 },
    { name: "SAR Commander", quantity: 20 },
    { name: "SORT", quantity: 35 },
    { name: "Search Advisor", quantity: 12 },
    { name: "Specialist Paramedic", quantity: 44 },
    { name: "Tactical Command Course", quantity: 6 }
];
